### ISSUE TITLE
کاربر با چند نقش

### ISSUE THREAD

**Issue by saeedrahmo** [VahidN/IdentityServerImageGallery#3]
در هنگام دادن چند نقش به کاربر خطای زیر صادر می شود آیا تنظیمات دیگری نیاز است؟

`An unhandled exception occurred while processing the request.
InvalidCastException: Cannot cast Newtonsoft.Json.Linq.JArray to Newtonsoft.Json.Linq.JToken.
Newtonsoft.Json.Linq.Extensions.Convert<T, U>(T token)

Exception: An error was encountered while handling the remote login.
Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler<TOptions>.HandleRequestAsync(`

**Comment by VahidN** [comment]
<div dir="rtl">

براي گزارش خطا هميشه stack trace كامل را ارسال كنيد تا مشخص باشد اين سطرها متعلق به كدام قسمت برنامه هستند.

همچنين [اين تعريف منحصربفرد](https://github.com/VahidN/IdentityServerImageGallery/blob/7ea885d55a01e8d4ac72dd275e5124f8a9c103e9/src/IDP/DNT.IDP.DataLayer/Configurations/UserClaimConfiguration.cs#L36) بودن user-claim هم غيرضروري است و با بودن آن چند نقش را نمي‌شود ثبت كرد.

**Comment by saeedrahmo** [comment]
<div dir="rtl">

فکر نمیکنم خطا مربوط به IDP باشد  
برای stack trace کامل چه تنظیماتی باید اضافه کرد صفحه خطا محل وقوع را نشان نمی دهد

**Comment by VahidN** [comment]
<div dir="rtl">

اين چند نقش را كجا اضافه كرديد؟ (مراحل باز توليد را اگر توضيح دهيد مهم است)
همچنين اگر برنامه را از طريق فايل‌هاي bat اي كه به همراه پروژه‌ها است اجرا كنيد، در كنسول، خطاي كامل به همراه استك‌تريس قابل مشاهده هستند. 
روش اجراي برنامه‌ها را از طريق فايل‌هاي bat همراه اين پروژه‌ها در ذيل هر قسمت اين سري و يا در فايل [readme](https://github.com/VahidN/IdentityServerImageGallery/blob/master/README.md) مي‌توانيد مشاهده كنيد
يا فايل _1-[dotnet_run_all.bat](https://github.com/VahidN/IdentityServerImageGallery/blob/master/_1-dotnet_run_all.bat) را اجرا كنيد. ساده و سريع است.

**Comment by saeedrahmo** [comment]
<div dir="rtl">

برای قسمت IDP بنده از پروژه [IdentityServer4.Admin](https://github.com/skoruba/IdentityServer4.Admin) استفاده کردم و برای mvcclient و webapi از پروژه شما استفاده کردم شما role را بصورت claim به کاربر دادید ولی من از جدول userrole استفاده کردم و claim کاربر حذف role دادم زمانی که فقط PayingUser باشد کار می کند اما وقتی چند role باشد خطا می دهد 


<div dir="ltr">

```
fail: Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler[17]
      Exception occurred while processing message.
System.InvalidCastException: Cannot cast Newtonsoft.Json.Linq.JArray to Newtonsoft.Json.Linq.JToken.
   at Newtonsoft.Json.Linq.Extensions.Convert[T,U](T token)
   at Newtonsoft.Json.Linq.JToken.Value[T](Object key)
   at Microsoft.AspNetCore.Authentication.OpenIdConnect.Claims.UniqueJsonKeyClaimAction.Run(JObject userData, ClaimsIdentity identity, String issuer)
   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.GetUserInformationAsync(OpenIdConnectMessage message, JwtSecurityToken jwt, ClaimsPrincipal principal, AuthenticationProperties properties)
   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.HandleRemoteAuthenticateAsync()
```

```
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
System.Exception: An error was encountered while handling the remote login. ---> System.InvalidCastException: Cannot cast Newtonsoft.Json.Linq.JArray to Newtonsoft.Json.Linq.JToken.
   at Newtonsoft.Json.Linq.Extensions.Convert[T,U](T token)
   at Newtonsoft.Json.Linq.JToken.Value[T](Object key)
   at Microsoft.AspNetCore.Authentication.OpenIdConnect.Claims.UniqueJsonKeyClaimAction.Run(JObject userData, ClaimsIdentity identity, String issuer)
   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.GetUserInformationAsync(OpenIdConnectMessage message, JwtSecurityToken jwt, ClaimsPrincipal principal, AuthenticationProperties properties)
   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.HandleRemoteAuthenticateAsync()
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```
برای رفع این خطا این کدها را اضافه کردم اما رفع نشد

```
 options.Events = new OpenIdConnectEvents()
                  {
                      OnUserInformationReceived = async context =>
                      {
                          // IDS4 returns multiple claim values as JSON arrays, which break the authentication handler
                          if (context.User.TryGetValue(JwtClaimTypes.Role, out JToken role))
                          {
                              var claims = new List<Claim>();
                              if (role.Type != JTokenType.Array)
                              {
                                  claims.Add(new Claim(JwtClaimTypes.Role, (string)role));
                              }
                              else
                              {
                                  foreach (var r in role)
                                      claims.Add(new Claim(JwtClaimTypes.Role, (string)r));
                              }
                              var id = context.Principal.Identity as ClaimsIdentity;
                              id.AddClaims(claims);
                          }
                      }};
```

**Comment by VahidN** [comment]
<div dir="rtl">

احتمالا [نگاشت‌ها را تعريف نكرديد](https://github.com/VahidN/IdentityServerImageGallery/blob/d6fd6c13c5460df3c2b432baa7826848d5d5ca3b/src/MvcClient/ImageGallery.MvcClient.WebApp/Startup.cs#L83)
https://github.com/aspnet/AspNetCore/issues/4669#issuecomment-361505163

**Comment by saeedrahmo** [comment]
<div dir="rtl">
کدی که استفاده کردم بصورت زیر می باشد

<div dir="ltr">


```
       services.AddAuthentication(options =>
            {
                options.DefaultScheme = "Cookies";
                options.DefaultChallengeScheme = "oidc";
            }).AddCookie("Cookies", options =>
              {
                  options.AccessDeniedPath = "/Authorization/AccessDenied";
              })
              .AddOpenIdConnect("oidc", options =>
              {
                  options.SignInScheme = "Cookies";
                  options.Authority = Configuration["IDPBaseAddress"];
                  options.ClientId = Configuration["ClientId"];
                  options.ResponseType = "code id_token";
                  //options.CallbackPath = new PathString("...")
                  //options.SignedOutCallbackPath = new PathString("...")
                  options.Scope.Clear();

                  options.Scope.Add("openid");
                  options.Scope.Add("profile");
                  options.Scope.Add("address");
                  options.Scope.Add("roles");
                  options.Scope.Add("imagegalleryapi");
                  options.Scope.Add("subscriptionlevel");
                  options.Scope.Add("country");
                  options.Scope.Add("offline_access");

                  options.SaveTokens = true;
                  options.ClientSecret = Configuration["ClientSecret"];
                  options.GetClaimsFromUserInfoEndpoint = true;

                  options.ClaimActions.Remove("amr");
                  options.ClaimActions.DeleteClaim("sid");
                  options.ClaimActions.DeleteClaim("idp");
                  // options.ClaimActions.DeleteClaim("address");

                  options.ClaimActions.MapUniqueJsonKey(claimType: "role", jsonKey: "role", valueType: "role");
                  options.ClaimActions.MapUniqueJsonKey(claimType: "subscriptionlevel", jsonKey: "subscriptionlevel");
                  options.ClaimActions.MapUniqueJsonKey(claimType: "country", jsonKey: "country");
                  
                  options.TokenValidationParameters = new TokenValidationParameters
                  {
                      NameClaimType = JwtClaimTypes.GivenName,
                      RoleClaimType = JwtClaimTypes.Role,
                  };

                  options.Events = new OpenIdConnectEvents()
                  {
                      OnUserInformationReceived = async context =>
                      {
                          // IDS4 returns multiple claim values as JSON arrays, which break the authentication handler
                          if (context.User.TryGetValue(JwtClaimTypes.Role, out JToken role))
                          {
                              var claims = new List<Claim>();
                              if (role.Type != JTokenType.Array)
                              {
                                  claims.Add(new Claim(JwtClaimTypes.Role, (string)role));
                              }
                              else
                              {
                                  foreach (var r in role)
                                      claims.Add(new Claim(JwtClaimTypes.Role, (string)r));
                              }
                              var id = context.Principal.Identity as ClaimsIdentity;
                              id.AddClaims(claims);
                          }
                      }};

                  });
```

**Comment by VahidN** [comment]
<div dir="rtl">

نياز به options.Events نيست. فقط قسمت MapUniqueJsonKey بايد تبديل به MapJsonKey شود

<div dir="ltr">

```csharp
options.ClaimActions.MapJsonKey(claimType: "role", jsonKey: "role"); // for having 2 or more roles
```
